### ISSUE TITLE
Remove job from Agenda

### ISSUE THREAD

**Issue by Boscop** [mehcode/schedule-rs#12]
Is it possible to remove a job from an Agenda without having to reconstruct the whole agenda?
It would be very useful. Jobs could be added with a name / ID and then removed with the name / ID.

Also it would be useful to be able to pause/continue jobs by name / ID.

**Comment by mehcode** [comment]
@Boscop Short answer, not yet but we will.

I've got a lot planned for the next version of this crate.

```rust
    let mut a = Agenda::new();

    // Named: Add - Run every minute
    a.define("task", || {
        // [...]
    }).schedule_limit("@every 1m", 1);

    // Named: Remove
    a.remove("task");

    // Unnamed: Add - Run every hour
    a.add(&some_function).schedule(Duration::hours(1));

    // Unnamed: Remove
    a.remove(&some_function);

    // Schedule - every 10 minutes for the next 10 times
    a.schedule_limit("*/10 * * * *", "task", 10);

    // Schedule a function directly; closest to what we have in 0.1
    a.schedule("*/5 * * * *", &some_other_function);
```

Depending on how it goes making that work, it might change a bit. But I like to have an idea of an API before I get started.

They key bit is separating a Job from its Definition.

**Comment by mehcode** [comment]
Done. Check the examples.
