### ISSUE TITLE
Thread-pool Dispatch of Jobs

### ISSUE THREAD

**Issue by stephanbuys** [mehcode/schedule-rs#6]
@mehcode want to add?

**Comment by mehcode** [comment]
@stephanbuys If you're asking if you want to add it? Sure. Is there a neat way to do a thread pool in Rust? I haven't looked into it.

**Comment by stephanbuys** [comment]
Full disclosure, this was a copy-paste from your reddit post, not 100% what is meant by it :-)

**Comment by mehcode** [comment]
Moving to a more general discussion at #15
