### ISSUE TITLE
Blocking run (instead of polling approach on readme)

### ISSUE THREAD

**Issue by stephanbuys** [mehcode/schedule-rs#7]
Block thread until timer expires.

**Comment by mehcode** [comment]
Should probably have a way to determine the minimum poll interval as well.

**Comment by mehcode** [comment]
Should probably also look into tokio here

**Comment by mehcode** [comment]
Going to wait for the community to recommend an approach and promote it to be added in the crate. It's only a couple lines to integrate this crate into an existing system.
